DROP DATABASE IF EXISTS bamazon;
CREATE database bamazon;

USE bamazon;

CREATE TABLE products(
    ITEM_ID INT NOT NULL,
    PRODUCT_NAME VARCHAR(255),
    DEPARTMENT_NAME VARCHAR(255),
    PRICE DECIMAL(18,2),
    STOCK_QUANTITY INT,
    PRODUCT_SALES DECIMAL(18,2),
    PRIMARY KEY (ITEM_ID)
);

CREATE TABLE departments(
    DEPARTMENT_ID INT NOT NULL,
    DEPARTMENT_NAME VARCHAR(255),
    OVER_HEAD_COSTS DECIMAL(18,2),
    PRIMARY KEY (DEPARTMENT_ID)
);